### ISSUE TITLE
docker composition - issues with recaptcha / env variables in the web container

### ISSUE THREAD

**Issue by pmauduit** [bfritscher/fablab-admin#73]
While trying to launch the composition, I ended up with the following message:

```
web_1    |   File "/app/fablabadmin/settings.py", line 219, in <module>
web_1    |     RECAPTCHA_PRIVATE_KEY = env('RECAPTCHA_PRIVATE_KEY')
web_1    |   File "/usr/local/lib/python2.7/site-packages/environ/environ.py", line 111, in __call__
web_1    |     return self.get_value(var, cast=cast, default=default, parse_default=parse_default)
web_1    |   File "/usr/local/lib/python2.7/site-packages/environ/environ.py", line 253, in get_value
web_1    |     raise ImproperlyConfigured(error_msg)
web_1    | django.core.exceptions.ImproperlyConfigured: Set the RECAPTCHA_PRIVATE_KEY environment variable
```

I followed the doc and created a `.env` file (leaving the default values from the readme though), and checked the `docker-compose.yml` file. I was not aware of a `env_file` directive, and was wondering if the fact that `env_file` and `environment` were both defined could lead to the issue, but removing the `environment` section in the docker-compose did not solve the problem.

**Comment by bfritscher** [comment]
Unfortunately, for now it is not optional, try getting a key from https://www.google.com/recaptcha/admin
and copy both keys from step 2 server integration:
RECAPTCHA_PRIVATE_KEY=yourkey
RECAPTCHA_PUBLIC_KEY=yourkey
either directly in the env part of the compose file or in the .env

**Comment by pmauduit** [comment]
Ok, so there is a check that provided keys are correct when the application starts, I thought that having them defined (even with fake variables) would suffice, thanks for the answer

**Comment by pmauduit** [comment]
Ok, while ansibilizing the application, I guess I found out why I got an issue with the environment variables definitions. I suspect the simple quotes to make the env variables failing (or maybe the spaces between variable names, the '=' sign and the actual value), the following template for my `.env` file is working (following variables are obviously fake):

```
RECAPTCHA_PRIVATE_KEY=aodkpaodkpwokpawodkw
RECAPTCHA_PUBLIC_KEY=qowdkpqoowkdpqowkdpqwokdqpwok

```
